# Generated by Django 5.2.8 on 2025-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Описание"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("accepted", "Принят в работу"),
                            ("completed", "Выполнена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="new",
                        max_length=100,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("operator", "Оператор"),
                            ("monitoring", "Мониторинг"),
                            ("partner", "Партнер"),
                        ],
                        default="monitoring",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Инцидент",
                "verbose_name_plural": "Инциденты",
                "ordering": ("-pk",),
            },
        ),
    ]
